spring:
  data:
    mongodb:
      uri: mongodb://root:P4ssword!@localhost:27017/BackendSpringboot
      database: BackendSpringboot

  # Configuración de JPA e Hibernate (MongoDB no usa Hibernate, por lo que puedes eliminar esta sección en su totalidad si no es necesaria para alguna otra parte)
  jpa:
    hibernate:
      ddl-auto: none  # MongoDB no necesita ddl-auto ya que no usa SQL
    open-in-view: false

  # Configuración de JWT para autenticación y autorización
jwt:
  secret: securesecretkey # Clave para firmar el JWT. Cambia a una clave segura.
  expiration: 86400000 # Duración del token en milisegundos (24 horas)

# Configuración del servidor
server:
  port: 8080 # El backend corre en el puerto 8080

# Configuración de CORS para permitir la comunicación desde el frontend (puerto 8082)
# La configuración de CORS se realiza principalmente en el archivo de configuración de seguridad (SecurityConfig.java)

# Configuración de manejo de errores
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR

# Configuración de logging
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    com.myproyect.springboot: DEBUG

# Configuración de Spring Actuator para exponer todos los endpoints de gestión
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
